[phases.setup]
nixPkgs = [
"python312",
"cmake",
"gcc",
"chromium"
]

[phases.build]
cmds = [
"python -m venv venv",
"source venv/bin/activate && pip install -r requirements.txt"
]

[start]
cmd = "source venv/bin/activate && PYTHONPATH=src python main.py"